import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount } from 'wagmi';

import NotConnected from '@/components/NotConnected';
import NewTodo from '@/components/NewTodo';
import TodoList from '@/components/TodoList';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { isConnected } = useAccount();

  return (
    <>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <ConnectButton />
          {isConnected ? (
            <div>
              <NewTodo />
              <TodoList />
            </div>
          ) : (
            <NotConnected />
          )}
        </div>
      </main>
    </>
  );
}
